### ISSUE TITLE
Trim All User Input from Text Fields

### ISSUE THREAD

**Issue by jlbooker** [AppStateESS/InternshipInventory#349]
Trim all user input from text fields before inserting it into the database. People are typing spaces before and after names (mostly Agency/host names) and cities, which makes finding unique entries difficult for reporting.

**Comment by caldwellc1** [comment]
@jlbooker Should I also check the students name and other student information since the information is changeable? Also does text fields include input with numerical values such as phone number and zip code? I've read that you could trim numbers like strings and it would later use the number as an integer, but I'm not entirely sure if this is always the case.
