### ISSUE TITLE
Restore major fields in CSV export

### ISSUE THREAD

**Issue by jlbooker** [AppStateESS/InternshipInventory#370]
In Internship::getCsv(), we need to use the `major_description` field to output the undergrad or graduate major (as determined by the `level` field). Be sure this is consistent when the major/level is not selected, and that the proper number of fields are always in the CSV output (so columns do not become misaligned).

**Comment by caldwellc1** [comment]
@jlbooker I think it might be better to fix this problem in the issue where I created the generic student types. It still has the same problem though since I based it on the previous code and did not fully check the csv as I now know how to. Since it hasn't been merged yet I can still add it to the pull request for that issue.
